# Aquestes són les variables que "ompliran" els teus fitxers de Kubernetes
replicaCount: 3

image:
  repository: sulejk/my-cicd-app
  tag: "27057cd9eed0221fef4b7b10d5f81e32dc285899"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30080