# Aquestes són les variables que "ompliran" els teus fitxers de Kubernetes
replicaCount: 3

image:
  repository: sulejk/my-cicd-app
  tag: "087414d1b113116cc94991603517b590c2c58522"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30080